[package]
name = "maths"
version = "0.1.0"
authors = ["Romain Vaillant <git@rphv.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
